[package]
name = "ndf"
version = "0.1.0"
authors = ["kiobu <cdolson30@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "3"
sysinfo = "0.35.1"
clap = { version = "4", features = ["derive"] }
